CREATE DATABASE IF NOT EXISTS task_tracker;

USE task_tracker;

CREATE TABLE IF NOT EXISTS tasks(
id int auto_increment PRIMARY KEY,
title VARCHAR(255) NOT NULL,
completed BOOLEAN NOT NULL DEFAULT FALSE
);